### ISSUE TITLE
KeyError / SiftExtraction.use_gpu Error when running stereo_pipeline.py

### ISSUE THREAD

**Issue by SBCV** [Kai-46/VisSatSatelliteStereo#1]
Thank you for releasing your source code. Unfortunately, running your pipeline with the MVS3D imagery throws an error message.

When executing `python3 stereo_pipeline.py --config_file aoi_config/MVS3DM_Explorer.json`, I receive the following error message:
```
  File "VisSatSatelliteStereo/stereo_pipeline.py", line 115, in run
    self.run_colmap_sfm_perspective()
  File "VisSatSatelliteStereo/stereo_pipeline.py", line 346, in run_colmap_sfm_perspective
    colmap_sfm_perspective.run_sfm(work_dir, sfm_dir, init_camera_file, weight)
  File "VisSatSatelliteStereo/colmap_sfm_perspective.py", line 97, in run_sfm
    after_bundle_params = after_bundle_cameras[img_name]
KeyError: '0000_WV03_14NOV15_135121-P1BS-500171606160_05_P005.png'
```
After some investigation I found that in `colmap_sfm_perspective.py` the following line
`colmap_sfm_commands.run_point_triangulation(img_dir, db_file, tri_dir, init_template, reproj_err_threshold, reproj_err_threshold, reproj_err_threshold)` produces "empty" results (i.e. `cameras.txt, images.txt, poinits3D.txt` are empty)

Running the first command in the corresponding log file (`log_sfm_perspective.txt`) 
```
Running subprocess: colmap feature_extractor --database_path /mnt/DataSSD/SpaceNet/MVS3D_wd/colmap/sfm_perspective/database.db --image_path /mnt/DataSSD/SpaceNet/MVS3D_wd/colmap/sfm_perspective/images --ImageReader.camera_model PERSPECTIVE --SiftExtraction.max_image_size 10000 --SiftExtraction.estimate_affine_shape 0         --SiftExtraction.domain_size_pooling 1 --SiftExtraction.max_num_features 25000 --SiftExtraction.num_threads 32 --SiftExtraction.use_gpu 1 --SiftExtraction.gpu_index -1
```
causes 
```
==============================================================================
Feature extraction
==============================================================================

Killed
```

The same error is thrown when I call the above command (except for the `--ImageReader.camera_model PERSPECTIVE`) for the original colmap library (https://github.com/colmap/colmap).

Any ideas what could be the cause of this? 

I think it would be nice if the pipeline (VisSatSatelliteStereo) would throw an appropriate error message and not something like `KeyError: '0000_WV03_14NOV15_135121-P1BS-500171606160_05_P005.png'`. 

Best regards,
Sebastian

**Comment by SBCV** [comment]
I just observed that `--SiftExtraction.use_gpu 1` works fine with `--SiftExtraction.domain_size_pooling 0`

**Comment by SBCV** [comment]
If I omit the `--SiftExtraction.num_threads 32` parameter, the feature extraction step works as expected.

**Comment by Kai-46** [comment]
(Reopening for the others to reference) Yes, that '--SiftExtraction.num_threads 32' is set for the compute resources where 4 TITAN GPUs are available. One should adapt the setting according to the amount of available resources.
