### ISSUE TITLE
reparam_depth issue

### ISSUE THREAD

**Issue by sebasmurphy** [Kai-46/VisSatSatelliteStereo#2]
I'm running into an issue running the Sfm and MVS portions of the pipeline.  The initial steps `clean_data, crop_image, derive_approx, choose_subset, colmap_sfm_persepctive' all run to completion successfully on the `explorer` dataset.

Once the reparam_depth portion of the pipeline initializes it immediately fails on line 99 (reparm_depth.py)
`min_z_values = np.percentile(z_values, 1) - margin`

Looks like this is failing because my `z_values` list is empty which is due to the fact that the`points3D.txt` in my sparse output folder doesn't contain any data. It seems that this is supposed to be populated as part of the colmap process but for some reason no data is being written. 

Has anyone experienced this problem or is there possibly a step that I'm missing?

**Comment by Kai-46** [comment]
I suspect your  'colmap_sfm_perspective' might not run successfully. You can check the log file and see if there's any error inside it.

**Comment by sebasmurphy** [comment]
There was def an issue with `colmap_sfm_perspective`. I wasn't seeing anything in the console but you were correct that the logs were showing error. Looks like it was an issue with the box that I"m running on, which currently doesn't have a cuda graphics card. I was able to run successfully on a different box.

Thanks for the help.

**Comment by Kai-46** [comment]
Glad that you managed to fix it! For this codebase, all the console logs are re-directed to files.
