### ISSUE TITLE
Worldview images 

### ISSUE THREAD

**Issue by franjamonga** [Kai-46/VisSatSatelliteStereo#3]
First of all, congratulations on such a great job. My question is the following;
In my case I have downloaded Wolrdview -2 images which have the following metadata files:

original image in tif format, 
file with extension .ATT
file with extension .EPH
file with extension .GEO
file with extension .IMD
file with extension .RPB
file with extension .TIL
file with extension .XML
I would like to know how I can use your tool with this data, what steps should I take.

Thanks for your attention

**Comment by Kai-46** [comment]
Sorry for the late response. I've been swamped by another project. I believe .XML contains the RPC camera parameters. But I'm not sure what you image files are. The extension for worldview-3 images are .NTF. Once you figure out what are the image files, you might want to take a look at the [clean_data.py](https://github.com/Kai-46/VisSatSatelliteStereo/blob/master/clean_data.py), which converts the raw data to a format that can be used by subsequent steps.
